repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
        exclude: ^recipe/meta*.yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        additional_dependencies: ["toml"]
        files: ^src/(.*/)*.*\.py$
# Comment this entry and uncomment that below to use local mypy (see notes below)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
# Uncomment to run conda locally, e.g., when developing a tool that is available
# on anaconda in order to prevent pre-commit from installing the latest version
# instead of testing the local code
#-   repo: local
#    hooks:
#    -   id: mypy
#        name: mypy
#        language: system
#        types: [python]
#        entry: mypy
#        require_serial: true
-   repo: local
    hooks:
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: python
        additional_dependencies:
          - jupyter
          - nbconvert
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
          - mccabe
